### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#10]
Syncs whitelisted accounts' tweets with matched tags to given Discord channels.

Commands:

`::twitter subscribe #channel <tag>` add a tag-channel link to a database
`::twitter unsubscribe <tag> (#channel ...)` remove a specific channel from tag table if the channel is provided, otherwise only remove given channel record
`::twitter list (#channel ...)` shows synced tag-channel globally or for specified channels
`::twitter allowlist list` shows whitelisted accounts
`::twitter allowlist add <twitter username/id>` adds twitterhandle to database as whitelisted account

Stolen from https://github.com/fit-ctu-discord/honza-botner/issues/2

**Comment by tenhobi** [comment]
Only for mods.

**Comment by tenhobi** [comment]
Can we somehow sync with list https://twitter.com/i/lists/1299407597624332294 ?

**Comment by tenhobi** [comment]
https://github.com/linvi/tweetinvi

**Comment by stepech** [comment]
Is this still relevant?

**Comment by pokorj54** [comment]
Nowadays, it seems that nobody is using the previous tags on twitter anymore. 
Also, I think there is now a pricing issue - free tier allows only posting.
