### ISSUE TITLE
Add audio streaming feature

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#103]
Just copy some music bot lol

**Comment by ostorc** [comment]
"Just" "copy" "music bot"... Ok 😩

**Comment by pokorj54** [comment]
I was too lazy to type everything. It is certainly not a priority, and I did not want to make it sounds like it is too easy, but I think the concept is well known, so I do not even have to write it for you to understand.

**Comment by ostorc** [comment]
I didnt mean it that that way ❤️. But lets put aside the complexity of writing the code.
1. Do we really need to copy Muzikar bot functionality?
2. Will Heroku be able to handle it?

**Comment by pokorj54** [comment]
Rhythm bot is not talking to me right now. He heard @tenhobi singing a song from Adam Kajumi so I am worried if he is alright, I think this could have affected his mental health so much that he will not be the same bot as we know him.

**Comment by tenhobi** [comment]
@pokorj54 why are we arguing again? 😂

**Comment by tenhobi** [comment]
Google now promotes the ban of music bots.
