### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#11]
`.help` will show all available command for normal user with command description
`.help admin` if the user is admin it will show allowed admin commands with description

**Comment by tenhobi** [comment]
Maybe we can use `mod` to keep sync between discord roles?

**Comment by ostorc** [comment]
This will be implemented through CommandNexts, where we can set description to each command and its parameters. Also this allow us to group command (admin commads, auth commands, ..)
