### ISSUE TITLE
Mute

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#111]
Adds mute functionality -- uses `Sock of Silence` role

- [ ] `::mute <user> <timeout> <reason>`
- [ ] `::unmute <user>`

Enhance warning functionality:

- [ ] `::warn mute <time in minutes> <user> <reason>` - special case that add a warning and also mutes the user for given time

**Comment by tenhobi** [comment]
This will be a new feature in Discord. https://www.youtube.com/watch?v=35yTMzd9A-4&ab_channel=AndroidDiscord

**Comment by jirkavrba** [comment]
![](https://media0.giphy.com/media/hQidaBLsDmFXVSF9OU/200.gif)
