### ISSUE TITLE
Features used on VUT servers

### ISSUE THREAD

**Issue by sinus-x** [fit-ctu-discord/honza-botner#13]
**User motivation**
- **Karma**. User gains karma points when other react to their posts with emojis, which have value of `+1`, `0` or` -1`. The more reactions user gets, the more karma they recieve. ([example](https://github.com/sinus-x/rubbergoddess/tree/master/cogs/karma))
- **Points**, MEE6 style. For every minute user has been active (=they have sent a message to any of guilds channels), they are given 15-25 points. (implemented in [MEE6], [GrillBot])

**Management**
- **purge**: Message batch removal
- **dynamic replies**: Let the bot reply to defined triggers ([example](https://github.com/sinus-x/rubbergoddess/blob/master/cogs/actress/actress.py#L278))
- **autopin**: If more than _x_ users react with :pushpin: emoji, the message is pinned.

**Information commands**
- **latex**: Display latex output ([example](https://github.com/Czechbol/Amadeus/blob/master/cogs/draw.py#L92))
- **plot**: Display functiton graph ([example](https://github.com/Czechbol/Amadeus/blob/master/cogs/draw.py#L110))
- **nameday** ([example](https://github.com/sinus-x/rubbergoddess/blob/master/cogs/librarian/librarian.py#L24))
- **weather**, **forecast**: Lookup to [openweathermap API](https://openweathermap.org/api) ([example](https://github.com/sinus-x/rubbergoddess/blob/master/cogs/librarian/librarian.py#L63))
- **pick**, **random** ([example](https://github.com/sinus-x/rubbergoddess/blob/master/cogs/random/random.py))

Edit: Added pushpin

[GrillBot]: https://github.com/Misha12/GrillBot
[MEE6]: https://mee6.xyz/

**Comment by jirkavrba** [comment]
Latex, plot -> Mathbot?

**Comment by ostorc** [comment]
Does have Karma and Points any other effect than being able to compete with each other in spamming (not saying that's not an important thing)

**Comment by sinus-x** [comment]
> Latex, plot -> Mathbot?

We tend to remove third-party bots as soon as possible, because they may log all messages they can see without anyone knowing it. It just seems safer to have the privacy under controll, at least from the bot perspective.

> Does have Karma and Points any other effect than being able to compete with each other in spamming (not saying that's not an important thing)

You won't last long, if the only reason you're writing messages is to be leader in statistics. Karma does not suffer from this at all, as it's other users that have controll over your score. It also serves as a nice punishment if some user is trolling -- you don't need mod team, others just punish them with negative karma points.

**Comment by pokorj54** [comment]
Does karma have any effect other than to flex on others?

**Comment by ostorc** [comment]
If not, I think there will be some people which will flex even on negative karma (@Clown)

**Comment by jirkavrba** [comment]
We could add eg. people with karma < -200 cannot post to certain channels?

**Comment by sinus-x** [comment]
> Does karma have any effect other than to flex on others?

No.

Well, it motivates you to post content that others want to see, which may help in creating inviting, open place (or keeping it that way).
