### ISSUE TITLE
Bot does not answer to fun choose very long message

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#132]
When asking the bot to choose an option, but giving him only one option with maximum size, the bot gives me a thumbsup, but does not deliver the message.  Probably because his message is too long.

This also means that output to the user is handed incorrectly, because  I have mixed results - thumbs up meaning positive outcome, but no message, WHICH IS A BIG ISSUE! DO NOT SWALLOW EXCEPTIONS AND DO NOT PRETEND THAT NOTHING HAPPENED!!!!!

**Comment by tenhobi** [comment]
Actually the 👍 (`:+1:`) is the error output. 😄 There is s typo, it should be :-1: (`:-1:`).

**Comment by ostorc** [comment]
We have already implemented some solution for this. The issue right now is that we are swallowing exceptions as @pokorj54 said. We should go through all the commands and verify that they are not swallowing exception and letting them propagate.
