### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#14]
- [x] `.abc "question" "option one" "option two" ... "option n"` for creation of multichoice polls
- [x] `.yesno question` for creation of yes no poll
- [ ] Add custom emote for abc type poll

Do we want option to specify emojis in a multichoice poll?

Do we want option to say some form of closing of the polls?

**Comment by tenhobi** [comment]
We could use some strict syntax like this to 

`.abc "question" 👍"alpha" ⌚"beta" 🧄"gama" "omega" "blabla"`

Which would generate 

👍 alpha
⌚ beta 
🧄 gama 
D omega
E blablabla

**Comment by tenhobi** [comment]
Finished in https://github.com/ostorc/honza-botner-dev/pull/2

![image](https://user-images.githubusercontent.com/5287596/93238690-0fbbda80-f782-11ea-9ef4-21e44c2c5d5a.png)

**Comment by pokorj54** [comment]
> We could use some strict syntax like this to
> 
> `.abc "question" 👍"alpha" ⌚"beta" 🧄"gama" "omega" "blabla"`
> 
> Which would generate
> 
>  alpha
>  beta
>  gama
> D omega
> E blablabla

Is this also implemented?

**Comment by tenhobi** [comment]
That is not as simple as it sounds. We might use some regex like https://regex101.com/r/LcTTa6/1, but it's not perfect.

Or we might limit the API to emojis using discord codes `;poll "question" :thumbsup:"answer1" ...` (Hopefully they keep the codes in the text. :D

**Comment by ostorc** [comment]
There was one implementation of this issue, but due to change of background service I have commented it out, but rewriting it back to working code, should be pretty straightforward. @albru123 can you have look at this?
