### ISSUE TITLE
Custom status

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#143]
The bot has the ability to change activity, but it should also allow setting custom status and emoji. The activity verb is quite limiting.

**Comment by tenhobi** [comment]
Bots cannot implement custom activity/status (for now?).

https://github.com/DSharpPlus/DSharpPlus/issues/766

https://github.com/DSharpPlus/DSharpPlus/pull/498

**Comment by pokorj54** [comment]
Hmm, I see that [ActivityType](https://dsharpplus.github.io/api/DSharpPlus.Entities.ActivityType.html ) can be custom. Isn't that what we want?

**Comment by tenhobi** [comment]
... at least read the issues mentioned. xD "Bots cannot have custom statuses. You can set a listening or streaming activity with ActivityType.ListeningTo or ActivityType.Streaming."

**Comment by jirkavrba** [comment]
According to the Discord docs, the custom status should be available already

https://discord.com/developers/docs/topics/gateway#activity-object-activity-types
https://discord.com/developers/docs/topics/gateway#update-presence

**Comment by tenhobi** [comment]
No, that only works for human users, not for bot users. See for example https://support.discord.com/hc/en-us/community/posts/360054589611-Custom-Statuses-for-Bots. Or try it yourself. ;)
