### ISSUE TITLE
Add reaction to gain role functionality

### ISSUE THREAD

**Issue by jirkavrba** [fit-ctu-discord/honza-botner#15]
eg. Zira

**Comment by tenhobi** [comment]
This functionality copies `Zira` bot.

Watcher is made on a given message reaction and when an emote from the database occurs, a given role is assigned to a user.

Commands:

- `.addEmoteRole <message url> <emote> <role>` to add a record to the database
- `.removeEmoteRole <message url> <emote>` to remove a record from the database

This replaces Zira bot.

**Comment by tenhobi** [comment]
One emoji can have multiple assigned roles.

**Comment by tenhobi** [comment]
Waiting for https://github.com/fit-ctu-discord/honza-botner-dev/issues/44

**Comment by ostorc** [comment]
It is possible to implement this issue now. It will require adding new table to database, handlers and commands. The implementation is not so hard, but it will require to touch nearly all places in project.

**Comment by tenhobi** [comment]
Cool, will take a look at this. Hmm, do we wanna provide some other functionality above Zira's "normal" mode, like toggle (only 1 of N), etc.? 

This normal mode also works for multiple roles for one specific emoji, aka one emoji can add roles A, B, C, and so on, each having its own record in the table. Probably everything we need.
