### ISSUE TITLE
Emotes command - weird behaviour

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#151]
Sometimes I can use ``::emote`` command sometimes not. Also it probably accepts wrong arguments.

![image](https://user-images.githubusercontent.com/43776417/117536552-eba45680-affb-11eb-9cb8-5cc137605480.png)
![image](https://user-images.githubusercontent.com/43776417/117536565-fced6300-affb-11eb-8f11-b974b381627e.png)
![image](https://user-images.githubusercontent.com/43776417/117536571-0676cb00-affc-11eb-8981-4c7bb24b8add.png)

**Comment by stepech** [comment]
Might be connected 
![image](https://user-images.githubusercontent.com/29132060/135171883-24764392-be70-4277-a326-baff342ed5c1.png)

**Comment by tenhobi** [comment]
It's due to these commands have a limit on how many times a user can use them in a given time period. The error message is not descriptive in this situation at all. :D

**Comment by stepech** [comment]
We can easilly add error check for cooldown attribute and return specific message for that. Can I do this?
[Here](https://github.com/fit-ctu-discord/honza-botner/blob/b48ff5fb29b23314b6d5c7e79b58c490a7901f28/src/HonzaBotner.Discord/DiscordBot.cs#L149)

**Comment by tenhobi** [comment]
@stepech sure, error handler for this would be awesome. Also, not sure how they implement the Cooldown command attribute, but if we can modify it so the Mod has unlimited power there, it would be awesome.

**Comment by stepech** [comment]
Whoooh ok.. You've just made it from 5 minute fix to 30 minute research 😅Will do 😁
