### ISSUE TITLE
Add code documentation for framework-level code

### ISSUE THREAD

**Issue by jirkavrba** [fit-ctu-discord/honza-botner#154]
For example `EventHandlerResult` is really confusing without the `<summary>` documentation
@tenhobi

**Comment by ostorc** [comment]
Will make PR for it. It is not so complicated. It just says, that if the current event should be propagated and handled by other handlers, or if it should stop in the current handler. If you have some suggestions for better naming, it is welcome.

**Comment by stepech** [comment]
@ostorc is this issue done with #155 and can we close it or is there still something?
