### ISSUE TITLE
Pin types

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#164]
### Pin types

Most of the pins have a short life cycle, in 1-3 months. It would be beneficial if we would create another pin that would separate "pin me for a while" vs "pin me forever". That means we would detect these reactions:

- 📌 (`:pushpin`) aka "soft pin"
  - would act as it does now
  -  \+ it would be locked and removed from pins after --- ~~3 months~~ / on some special Mod only command, that will be run at the end of the semester, etc?
- 📍 (`:round_pushpin:`) aka "hard pin"
  - will stay forever -- current behavior of nowadays 📌
- 🔒 (`:lock:`) aka "antipin"
  - **only works while given by the bot or Mod**
  - will suppress from later pinning with either type of the pin (only if given by the bot or Mod)
  - unpins the message

### Command

`::pin delete all` / `::pin delete <channel ID>` (alias purge, ... -- take a look and copy the aliases from other commands) => for each pinned message, take a look at the message. If it doesn't have > threshold of 📍 reactions, it will be unpinned and the 🔒 (means it will antipin the message) will be given.

Use interactivity to confirm deletion. -> https://github.com/fit-ctu-discord/honza-botner/blob/master/src/HonzaBotner.Discord.Services/Commands/MessageCommands.cs#L48

**Comment by ekkomaru** [comment]
I'll have a look at this during the week.

**Comment by jirkavrba** [comment]
How about using the `:pushpin:` like a queue (there is a limit of 50 pinned messages / channel IIRC) ?
So once a message should be pinned and there is 50 messages pinned already, it unpins the oldest message pinned with `:pushpin:`

**Comment by tenhobi** [comment]
That's a nice idea. But IMHO in general (stats), in some channels, there is one pin, in some there are tens. All valid in the semester, but not necessary later. Limiting it to some number is neither beneficial for all cases, neither valid for a lot of channels with too few pins.

**Comment by jirkavrba** [comment]
Ok boomer, makes sense :smile:

**Comment by stepech** [comment]
čest
