### ISSUE TITLE
News from courses

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#169]
Courses allow having a special news page. The news can be seen in JSON. 

I request a feature that will post the news into the corresponding subject channel.

**Comment by pokorj54** [comment]
There may be a problem that the news are not open to the public for all subjects. So how to get access to that? @jmeinlschmidt did the help pages for courses so he may be more informed.

**Comment by ostorc** [comment]
Overview of the feature: https://help.fit.cvut.cz/courses/content/news.html
Some more detailed documentation is here: https://gitlab.fit.cvut.cz/course-pages/course-pages/blob/master/man/NEWS.adoc.5.adoc

**Comment by ostorc** [comment]
Courses API documentation: https://courses.fit.cvut.cz/api/v1/doc.html#/paths/~1cpages~1news/get

**Comment by ostorc** [comment]
Implementation of this should be quite similar to #10, both of these issues have same cycle:
1) get info about the data to fetch
2) fetch data from external service (only practical difference in implementation)
3) get diff, and select only new data
4) post it to correct channel (we could have here some custom formatting per type of data fetched...)
