### ISSUE TITLE
Commands in threads

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#198]
Commands don't work in threads even if the bot is there.

Not sure if we need to handle this, considering #65 slash commands will be implemented soon.

**Comment by stepech** [comment]
Actually solved on branch upstream/4.2. Will wait for library update. Should we close this?

**Comment by tenhobi** [comment]
> Actually solved on branch upstream/4.2. Will wait for library update. Should we close this?

Not merged, not closed.
