### ISSUE TITLE
CVUT Verification

### ISSUE THREAD

**Issue by jirkavrba** [fit-ctu-discord/honza-botner#2]
https://auth.fit.cvut.cz/manager

**Comment by pokorj54** [comment]
Can we detect if someone is from FIT or from other faculty?

**Comment by ostorc** [comment]
In usermap you can see all roles which you have. SO I think it should be possible to get them (at least most of them) too.
![image](https://user-images.githubusercontent.com/13519594/88584561-19627500-d052-11ea-8d56-fec7b9e8f68e.png)

**Comment by tenhobi** [comment]
After successful authentication, we should remove Budoucí prvák and Brno roles.

**Comment by tenhobi** [comment]
@ostorc I think B-18000 is for FIT only? Aka B-18000-OSOBA-CVUT should be a student or employee from FIT?

![image](https://user-images.githubusercontent.com/5287596/93104136-c13d0c00-f6ad-11ea-9cac-613baabba541.png)

I would only validate people from FIT. Others can be manually authenticated if needed.

**Comment by tenhobi** [comment]
Also, if the person has something other than `000` after `18`, they are probably some kind of employee

![image](https://user-images.githubusercontent.com/5287596/93104337-ffd2c680-f6ad-11ea-9a25-0a941e078f6a.png)

Aka we might automatically assign a role Teacher, ICT, PR etc.

**Comment by tenhobi** [comment]
Not sure we can sync that, because we do not preserve the token, but at least the initialization of each person might be ease of work.

**Comment by pokorj54** [comment]
Can we have a role with automatic assigning for doctoral students as well? 

Also, why is the mapping done with ids, it is very unclear what each role is. We know the name of source, but it might be confusing which role we are assigning on discord. 
Is it a good solution to name them before assigning them, some roles are used multiple times and it gives sense to me.
