### ISSUE TITLE
Reminder improvements

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#221]
- [x] After the reminder is done, keep the reactions.
- [x] Check if reminder actually reminds all the people because it probably reminded like half of them only. :(
- [x] Also send a reminder to the channel.

**Comment by pokorj54** [comment]
There should be seen the exact time of the reminder not just a date.

**Comment by pokorj54** [comment]
Also add preferable datetime format to the command manual/help page.
