### ISSUE TITLE
Send messages

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#28]
Admins should have the ability to send messages with the bot by command `.send #channel <message>`. Also admins should be able to edit that message with another command `.edit <messageID> <new message>`

* [x] send
* [x] edit
* [x] sendImage 
* [x] editImage

**Comment by pokorj54** [comment]
Should we use messageID or link to that message? Link is easier to grab.

**Comment by tenhobi** [comment]
I cannot remember why we chose the URL in the first bot? But I think we can determine server from context? Not sure if message ID can be the same in two different channels? cc @jirkavrba

**Comment by pokorj54** [comment]
I know that Zira bot uses only message IDs, but they also force you to specify working channel.

**Comment by jirkavrba** [comment]
You cannot receive message by just ID afaik, you need channel and then fetch the message within the channel

**Comment by tenhobi** [comment]
Checked the API, you can only find message in a specific channel. We can have `.edit #rules 12345` or `.edit <link>`. The version with <link> is uglier but clear.

**Comment by jirkavrba** [comment]
Imo it's simpler as you have to right click the message anyway (to get ID / link). Also you can click the link to go to mentioned message directly

**Comment by tenhobi** [comment]
![image](https://user-images.githubusercontent.com/5287596/93117862-bc815380-f6bf-11ea-8ce8-8a14816a97e0.png)

**Comment by tenhobi** [comment]
![image](https://user-images.githubusercontent.com/5287596/93117928-d0c55080-f6bf-11ea-8a03-f53ae68b375a.png)

**Comment by tenhobi** [comment]
Done in https://github.com/ostorc/honza-botner-dev/pull/2
