### ISSUE TITLE
Purge

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#29]
`.purge <number>` removes last `<number>` messages.

For mods only.

**Comment by pokorj54** [comment]
I do not think it is a good idea. 
1. This may cause an accidental removal of messages - what if you miscount or make an error? What if somebody posts relevant message just a second before you purge the mesages?
2. I don't think it goes with our principles to make an uncensored server. This will make deleting messages for mods easier with less thinking what should and what should not be allowed.

**Comment by tenhobi** [comment]
So we would only ban the user and leave tens/hundreds of messages there if some spammer joins our server?

**Comment by pokorj54** [comment]
1st scenario:
Person X: spam
Person X: spam
Person X: spam
Person Y: valueable information
Person X: spam
Person X: spam

Your command would either delete valuable information or would leave spam here.

2nd scenario:

Person X: spam
Person X: spam
Person X: spam
You kick person X
You start typing  remove 3 messages
Someone posts another message
You deleted someone elses message

3rd scenario

both you and another mod execurtes the command at ruffly same time, poof lots of messages gone.

And still my concerns from previous message apply. Maybe it will be usefull someday, but I am worried that now it will make more harm than good.

**Comment by tenhobi** [comment]
Also, when banned, we can choose to remove their messages. That's safer because we don't delete some good message from another user. 👍 
![image](https://user-images.githubusercontent.com/5287596/90758536-78c54500-e2df-11ea-9e74-015d31488392.png)

**Comment by pokorj54** [comment]
Yes this seems far better
