### ISSUE TITLE
Sync BI/NI badge on Staff/Booster role changes

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#298]
When a student-user changes their roles, they get the color from it. We want to preserve the "I am BI/NI student" meaning, so we want to add a badge to substitute that meaning.

Aka the bot, on (all staff + booster) role changes, checks if the user is a student, if they have one of those roles, and if so, adds a BI/NI badge.

**Comment by stepech** [comment]
Close
