### ISSUE TITLE
Exams reminder

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#30]
Is it possible to somehow fetch exams for each subject?

**Comment by pokorj54** [comment]
Probably it is since timetable gets them somehow, you can check the kosapi.

**Comment by pokorj54** [comment]
But I don't think it is a good idea, since big subjects have lots of exams and it would just create undesired spam.

**Comment by pokorj54** [comment]
The only good feature I see (but it will be hard to implement) is to check whether new event/exam is added to KOS and if students can now join them.
