### ISSUE TITLE
Poll reactions get removed

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#304]
After some time, new reactions get removed. Maybe `.Reactions` return bad state (or dunno) for some reason.

![image](https://user-images.githubusercontent.com/5287596/155000758-1d8ef260-997b-4142-8281-5e693c4b5523.png)

https://github.com/fit-ctu-discord/honza-botner/blob/develop/src/HonzaBotner.Discord.Services/EventHandlers/PollReactionsHandler.cs#L31-L33

**Comment by stepech** [comment]
fixed
