### ISSUE TITLE
Warning 

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#31]
This feature is for mods only, duh.

- [x] `::warn <user> reason` - adds a warning to given user. Bot will post a warning message to the channel, to the user's DM, and to the mods #warnings channel. The warning message written by the mod will be deleted.
- [x] `::warn purify <user> (<id, ...>)` - removes all (or only selected) warnings for the user (?)
- [x] `::warn list (<user...>)` would print all (or defined users) warnings (timestamp, username, reason)
- [x] send DM to the user (`This is your X. warning! <channel> - <reason>`)

**Comment by tenhobi** [comment]
When multiple users (based on a threshold, probably 5/10+) add emote `inappropriate`, the user gets automatically a warning. If this feature will be misused, users might be given some role to disable voting for warning.

**Comment by ostorc** [comment]
I agree with the warn command, but I think that the warnings by reactions aren't necessary. Also what is difference between .warn <user> reason and .warn #channel <user> reason

**Comment by tenhobi** [comment]
The message with command gets removed and replaced with the bot's warning. If a channel is specified, it gets sent to that channel, not to the current. That way mods can add warnings from some other channel. Dunno. That is maybe useless.

But we might want to add some log channels for warning. Visible only to mods and maybe ping mods if the number of recent warnings is more than some threshold.

**Comment by tenhobi** [comment]
I modified the API and requirements, also merged this with #35.

**Comment by tenhobi** [comment]
The mute feature is moved to separate issue #111.
