### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#32]
Make a simpler version of https://top.gg/bot/617376702187700224

`.thread init` (implicit) creates `THREADS` section
`.thread make <title> <description>` created 
`.thread keep` toggles a thread from/to being deleted due to inactivity.
`.thread lock` toogles a thread to/from being locked; members with the manage_message permission

This replaces Threadstorm bot.

**Comment by pokorj54** [comment]
I would wait on discord on their promised threads.

**Comment by ostorc** [comment]
Is this still required?

**Comment by tenhobi** [comment]
Not sure. There is a limit of channels available and I am not sure if this feature would help us while it removes history from specific channels. Also, the new react feature is kinda better than the previous quote.
