### ISSUE TITLE
Add messages sent by users stats

### ISSUE THREAD

**Issue by Mateorid** [fit-ctu-discord/honza-botner#36]
Something like they have on the MUNI discord server.
![image](https://user-images.githubusercontent.com/56208414/92383000-e067f680-f10d-11ea-91e4-4e1d8d4c3985.png)

**Comment by tenhobi** [comment]
Useful for: ??

Disadvantages: probably DB expensive (as it's per channel).

**Comment by ostorc** [comment]
Dup of #13. Closing,
