### ISSUE TITLE
Hall of fame

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#41]
Similar to #17, but the post will be reposted to `#hall-of-fame`. Possibly as :star:. (not messages authored by bots)

// The message will contain author, message and all images.

**Comment by pokorj54** [comment]
Still, there should be a manual option for this feature.

**Comment by tenhobi** [comment]
Now I believe that pasting screenshots is a superb solution than using a bot, 'cause you can express more context with screenshotting 2 comments etc. for example.
