### ISSUE TITLE
Add Reactions and Messages handler contracts and logic

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#44]
Make API similar to commands, where every reaction will be processed by `reaction handlers`.

Needed for Auth, Emoji counter to db and other stuff like zira-like adding roles.

**Comment by ostorc** [comment]
This API is implemented. Please see example handler https://github.com/fit-ctu-discord/honza-botner/blob/master/src/HonzaBotner.Discord.Services/Reactions/EmojiCounterHandler.cs

**Comment by tenhobi** [comment]
@ostorc what does `return IReactionHandler.Result.Continue;` do? Is this some kind of invoking for an inside implementation of the chain of commands or so?

**Comment by ostorc** [comment]
Some handlers may want to stop the execution for current reaction (for example Verification handler). In most cases you should return Continue. If you have issues with this approach we can talk about it. Also note that, the handlers are going to be executed in order as they were registered.
