### ISSUE TITLE
[Bug] Get rid of techical roles in role config

### ISSUE THREAD

**Issue by stepech** [fit-ctu-discord/honza-botner#475]
By the logic from Vic website, technical roles are used to grant some higher privileges in some specific university systems. Business roles on the other hand represent the current status of the person. As we have found out recently, some of the technical roles are not revoked after their corresponding business role is. We should switch checks to business roles to get up-to-date and correct info and avoid some KOS-specific setups which we don't understand.
![image](https://user-images.githubusercontent.com/29132060/209366776-0f0cc506-120b-42e5-a9f6-e656f7878d1f.png)

**Comment by stepech** [comment]
VIC was faster and got rid of Technical roles before us. I am not sure if they have some backwards compatibility in place, but there is now possibility that verification no longer works in some cases.

**Comment by JanBliznicenko** [comment]
> VIC was faster and got rid of Technical roles before us. I am not sure if they have some backwards compatibility in place, but there is now possibility that verification no longer works in some cases.

True, adding discord Teacher role no longer worked for me as the only teacher-like usermap role I have is `B-18102-KOS-UCITEL`

**Comment by stepech** [comment]
@JanBliznicenko do you also have B-18000-UCITEL or something like that?

**Comment by JanBliznicenko** [comment]
> @JanBliznicenko do you also have B-18000-UCITEL or something like that?

No, `B-18102-KOS-UCITEL` is the only role with "UCITEL" or anything similar in it.
I have many SUMA roles and 18000 roles, but only for student, doktorand, zamestnanec, pracovnik etc.

**Comment by stepech** [comment]
Solved
