### ISSUE TITLE
Other schools verification

### ISSUE THREAD

**Issue by ostorc** [fit-ctu-discord/honza-botner#5]
As was suggested on discord talk, we should provide an option for other schools students to verify themselves and get by that access to the server, so mods doesn`t have to do it manually.

We should support at least these schools:

- [ ] VUT
- [ ] MUNI

and maybe others.

**Comment by jirkavrba** [comment]
Maybe add non-cvut verification via email and match certain patterns? 

`*@fit.vut.br` -> role:691907282019155989 atd

**Comment by ostorc** [comment]
That's an option. I would prefer to use OAuth if possible, but if not, that sounds like reasonable alternative.

**Comment by sinus-x** [comment]
Just a note: FEKT is part of VUT.

We do have this e-mail matching implemented in Rubbergoddess and it works flawlessly.

**Comment by jirkavrba** [comment]
> That's an option. I would prefer to use OAuth if possible, but if not, that sounds like reasonable alternative.

We can use OAuth for CVUT sign-in, afaik VUT does have a SSO server, but there is no chance for us getting an app ID and app secret

**Comment by sinus-x** [comment]
We haven't been able to convince the IT department that we won't be threat to their system. There were also some GDPR issues they did not want to deal with.

**Comment by pokorj54** [comment]
Is this really needed? We still need future students to use the server and I don't see a special feature for students from other universities. ¯\\\_(ツ)\_/¯

**Comment by sinus-x** [comment]
This can automate the "I'm not from ČVUT but I want to be part of your server" comments mods have to deal with.
E-mail verification for strangers is easy to implement and it saves a lot of time when the feature is in production environment.

**Comment by tenhobi** [comment]
Zira-like feature does automate this well enough. The server is PRIMARILY for the FIT CTU users, so wasting time on this feature while we don't have other stuff done is useless.
