### ISSUE TITLE
Edit poll 

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#51]
Creator of the poll should be able to add extra answers to the poll.

```.polladd <link> another answer```

I think that other modification should not be possible, because it could change the meaning of the poll.

**Comment by tenhobi** [comment]
That should be ok to implement even without DB 👍

To simplify the API we might use the argument instead of another command:
`;poll add <link> "another answer"`

**Comment by tenhobi** [comment]
Maybe we can introduce some prefix to the title of embed, like `Poll: <topic>` to be able to parse the message and determine that the message is actually a poll.

**Comment by jirkavrba** [comment]
What about a poll wizard?
-> `;makepoll`
<- `gib type: 1. yesno 2. multiple choice ...`
-> `2`
<- `gib question`
-> `Something interesting`
<- `gib answers`
-> `1. Nemám čas dělám progtest`
-> `2. Sen o xxx jsem si ještě nesplnil`
<- `ok. * creates poll * `

**Comment by pokorj54** [comment]
I think it's too complicated. I don't want to write too many messages.
