### ISSUE TITLE
Failure to authenticate CTU profile

### ISSUE THREAD

**Issue by ghost** [fit-ctu-discord/honza-botner#531]
**Describe the bug**
No way to disable authentication if previous Discord account is deleted.

**To Reproduce**
Standard CTU profile authentication sequence.

**Expected behavior**
Additional button to unbind a profile on the error page.

**Screenshots**
<img width="1223" alt="screen" src="https://github.com/fit-ctu-discord/honza-botner/assets/96445142/cf0cc1e3-30cc-4077-bade-3a890d97a40c">

**Comment by ostorc** [comment]
This is wanted behavior. If you want to remove old binding contact mods.

**Comment by stepech** [comment]
Tracked in #478
