### ISSUE TITLE
Command parameter parsing

### ISSUE THREAD

**Issue by albertmoravec** [fit-ctu-discord/honza-botner#55]
Commands could receive parsed list of its declared parameters upon execution and the bot could also reject invalid commands based on this declaration. This way commands wouldn't have to be concerned with parameter parsing where not necessary.

Ideally command would be able to declare if it wants the parameters parsed or not, the required number of parameters, optional parameters etc.

**Comment by tenhobi** [comment]
Maybe will overwrap with #65

**Comment by ostorc** [comment]
This issue should be covered by extensive support from CommandsNext. We can also define custom parsers for custom values, so we should be OK with that.
