### ISSUE TITLE
Nemužu se ověřit

### ISSUE THREAD

**Issue by Valoneu** [fit-ctu-discord/honza-botner#552]
**Describe the bug**
Nemužu se ověřit

**To Reproduce**
1. kliknu na ověřit
2. přihlásím se
**Expected behavior**
ověří mě to

**Screenshots**
![image](https://github.com/user-attachments/assets/9f057def-74bb-430d-b34b-90fc4c97252f)

**Comment by ostorc** [comment]
Ahoj, můžeš mi prosím poslat do soukromých zpráv tvůj username?

**Comment by ostorc** [comment]
Vyřešeno v DMs.
