### ISSUE TITLE
Add OnChannelCreated handler

### ISSUE THREAD

**Issue by albertmoravec** [fit-ctu-discord/honza-botner#60]
In this handler, all channel-related initialization should be done. This would primarily be used for initializing restrictive channel roles (looking at you `Sock of Silence`) that have to be initialized manually on per-channel basis.

**Comment by ostorc** [comment]
Not really sure why we need this, can you give more detailed explanation?

**Comment by albertmoravec** [comment]
I don't quite remember the details, but there were attributes that you needed to assign to each new channel, like specific role permissions to that channel etc.

**Comment by ostorc** [comment]
That sounds reasonable, but is it necessary? Opinions @pokorj54, @tenhobi?

**Comment by tenhobi** [comment]
Sure, Sock of Silence (and maybe some other stuff like Mods and verified bots) would be great to automatically add to new channels and voice channels.

**Comment by ostorc** [comment]
Fine. Adding this handler shouldn't be issue. Do we want to introduce similar system as we have for reaction handers for OnChannelCreated, or will we go with some "hardcoded" functionality?

**Comment by tenhobi** [comment]
Will use simple API using #83.
