### ISSUE TITLE
Pomodoro functionality

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#61]
We would need some Pomodoro functionality to help people studying in voice channel/s.

The bot should be able to start Pomodoro when some user joins (after everyone leaves the bot would stop this activity) a specific channel (Study With Me). We have multiple options:

- ⭐ The best option would be if we could somehow send voice to the voice channel on pause/work events.
- Ping every member of the voice channel on pause/work events.

We might also consider some channel name updates (dunno the limits tho) aka every 1, 10, 30... ? seconds the name would update to `work 25:00`, `work 24:50`, `work 24:40`, ... `pause 5:00`, `pause 4:50`, ...

**Comment by jirkavrba** [comment]
Maybe consider adding a temporary role @pomodoro, that would be automatically assigned to all members in the selected voice channel, bot then can ping the users with a single tag.

**Comment by tenhobi** [comment]
Turns out the best option is probably using the external services that everybody uses anyways. Pings etc would be too spammy.
