### ISSUE TITLE
Horny-jail automation

### ISSUE THREAD

**Issue by jmeinlschmidt** [fit-ctu-discord/honza-botner#62]
Role assignment and welcome message in #horny-jail channel.

**Comment by ostorc** [comment]
By which criteria would you assign role for horny jail? By bonk reactions?

**Comment by tenhobi** [comment]
We can do a welcome message for sure, but I am not sure if assigning a role by the reaction is a good idea. It can be used in a different context and then our super-secret society will be discovered. 😱
