### ISSUE TITLE
Use slash commands instead of custom command prefix

### ISSUE THREAD

**Issue by NejakejTomas** [fit-ctu-discord/honza-botner#65]
Discord recently added new API for [Slash Commands](https://discord.com/developers/docs/interactions/slash-commands), which allows Discord to suggest the command (which is way better than remembering a ton of commands (which is hard)
![image](https://user-images.githubusercontent.com/40525630/104382702-e09a5780-552e-11eb-8656-aa6f7f00ce42.png)
and it is way more user-friendly); create global commands or commands specific to one server, supposedly even make commands without bot on the server

**Comment by tenhobi** [comment]
Seems nice. 

![image](https://user-images.githubusercontent.com/5287596/104436511-fdb24300-558d-11eb-912d-9cb90512c8c1.png)

![image](https://user-images.githubusercontent.com/5287596/104436700-318d6880-558e-11eb-805a-065b74c4bd69.png)

![image](https://user-images.githubusercontent.com/5287596/104436749-40741b00-558e-11eb-9ac5-02749d8276d9.png)

**Comment by ostorc** [comment]
We will postpone implementation of this issue, since DSharpPlus (and other clients in C#) doesnt supprt this feature yet. When it will be added we will implement it.

**Comment by ostorc** [comment]
This looks OK to use for this: https://github.com/IDoEverything/DSharpPlus.SlashCommands

**Comment by tenhobi** [comment]
> DSharpPlus.SlashCommands extension by IDoEverything (CabbageAdi) is now officially a part of DSharpPlus
> As of build 4.2.0-nightly-01008, we now ship the extension as part of DSharpPlus, in the DSharpPlus.SlashCommands package. If you're using Adi's extension currently, updating to the official package should be, as of writing this post, as easy as substituting the package reference. The extension is now available only in the nightly feed, however it will be available on NuGet when 4.2.0 stable is released.
> 
> I'd like to thank CabbageAdi for contributing the extension to the library. I would also like to thank all contributors to the extension for making it possible. As part of the merge, we've made effort to preserve the extension's commit history (via subtree), as well as the contributor list. The extension is currently licensed under MIT, and has a separate license to the rest of the library.

This will be implemented in DSharpPlus 4.2.0, https://github.com/DSharpPlus/DSharpPlus/pull/1094. We will start working on this once this is available.

Also, we need to determine if we want to move all current commands to slash commands.

**Comment by stepech** [comment]
WIP
