### ISSUE TITLE
New accounts admin commands

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#66]
All commands should use only Mods.

- [x] Account erasing 

When some user creates another Discord user account while they were authenticated on the previous (lost) account, they cannot authenticate with this new account. This is good and intended.

My propose is to create such functionality that we can erase the user by its username (internally it will compute the hash and erase the record with the previous one) and the user with the new account can complete the auth process then. Something like `/user erase [CTU username]`.

- [x] Account info

We should be able to get user info in Discord, aka get the whole Database record, to see user id, authId (ctu username hash), verify status etc. Something like `user info [CTU username]`

**Comment by ostorc** [comment]
Can I close it? @tenhobi

**Comment by tenhobi** [comment]
I have linked the issues from the PR, it will close automatically on merge. @ostorc
