### ISSUE TITLE
Basic admin commands

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#69]
- [x] Send message
- [x] Edit message
- ~Send image~
- ~Edit image~
- ~Send embed~ -> #76 
- ~Edit embed~ -> #76 
- [x] React to message

**Comment by pokorj54** [comment]
nice

**Comment by pokorj54** [comment]
Why are the checkboxes duplicated? Is that for embeds?

**Comment by tenhobi** [comment]
@pokorj54 Nothing is duplicated, it covers the commands we already have in the old bot. `.send [where] [text]` vs `.sendImage [where] [URL]`. Now we will have

`!image send/edit` and `!message send/edit`. Maybe `.post send/edit (optionally image) [body of command]`, not sure what is better right now.

**Comment by pokorj54** [comment]
Sorry, I thought that it is enough to send images the normal user way. But since I mentioned it would it be possible to send embeds?

**Comment by tenhobi** [comment]
I think we could do that, but we have to think about the way how to do it. Because it has a lot of fields to set up. So we can limit the fields we can use or use for example the Interactivity feature. https://dsharpplus.github.io/articles/interactivity.html

Anyway, that would also cover the send/edit image needs. (+ maybe now we don't even need to implement send/edit images, because Discord now removes URL if that is the only  thing the message contains)
