### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#7]
- a command that will tell the bot to notify you at the specified time (both relative and absolute option of specifying time)
- others could join the reminder by clicking on emoji on the command 
Možné užití
`.reminder 2020-06-06T12:00:00 implement reminders to honza botner`
`.remainder in 12h online fit beer`

**Comment by ostorc** [comment]
Should we support here only English or be able to handle Czech too?

**Comment by tenhobi** [comment]
Also, reacting :watch: should add the user to the reminder.
