### ISSUE TITLE
Discord bot commands

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#71]
- [x] Set bot presence activity (playing x, watching x, ...)
- [x] ...?

**Comment by ostorc** [comment]
Hmmm. And what activity do you want to have? Or just have some random quotes which we will rotate?
Like:
- Tryharding progtest
- Having mental breakdown at MARAST
- Plním si sen o X (choose one thing from FIT anketa)
- ...

**Comment by pokorj54** [comment]
I think it will be better if we can change it by command, for example, if some event is happening we will change it accordingly.

**Comment by ostorc** [comment]
Ok, I wasn't sure what exactly you have wanted. Should this message be somehow persistent? For example if we reboot the bot, the message will stay there (it will require to use some persistent storage for this, probably some form of table in DB).

**Comment by tenhobi** [comment]
I think it would be better to make it persistent.
