### ISSUE TITLE
Remove host roles on auth

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#74]
Remove host roles (Host, Budoucí prvák) after a successful auth.

**Comment by ostorc** [comment]
This can be done in "hacky way". We can add dummy mapping into JSON:
```json
{
"HostRole": <host_id>,
"BudouciPrvakRole": <prvak_id>
}
```

This will also require us to always call this line https://github.com/fit-ctu-discord/honza-botner/blob/93bff8635f1a8714c584356c67a98507b38452e3/src/HonzaBotner.Services/CvutAuthorizationService.cs#L67
