### ISSUE TITLE
Emoji usage

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#8]
Command for listing emojis and the number of times it has been used.
`.emojis` to list emojis sorted by number of uses per day
Optional argument `total` will display total nuber of uses of emojis and sort by it.
Optional argument `animated` will display only animated emojis. Similarly with `nonanimated`.

**Comment by ostorc** [comment]
- [x] Total
- [x] Per Day
- [x] animated
- [x] nonanimated

**Comment by tenhobi** [comment]
The output is not sorted.

**Comment by ostorc** [comment]
The current implementation has also issue with missing emojis. If it can find emoji in current guild, it will still try to fetch and that takes a time (quite a lot)
