### ISSUE TITLE
Fun module

### ISSUE THREAD

**Issue by tenhobi** [fit-ctu-discord/honza-botner#82]
We might add `!fun` command that can have some off topic functionality. The point is so we can remove Simp bot etc.

Ideas:
-  ~get random FIT quote (+ register & approve)~
- [x] decide 
- ...

**Comment by ostorc** [comment]
Random fit quote is not an issue, but what does decide mean?

**Comment by tenhobi** [comment]
In fit dungeon they have something like .decide "study" "playing games" etc.
