### ISSUE TITLE
Help for admins/mods

### ISSUE THREAD

**Issue by pokorj54** [fit-ctu-discord/honza-botner#86]
Either bot should recognize which commands you can write or there should be option for help command to display mod commands if you are mod.

**Comment by ostorc** [comment]
You (as mod) can ask bot to show you help for mod only commands, even if they are not at first visible in help list (::help). I will take a look, if we can display you them in the list (again, only for mods)

**Comment by pokorj54** [comment]
I know that I can do a help command for a specific command, maybe I did not write it clearly. I often do not remember the exact name of the command, and help does not list all commands I can use, so I want to have a way to display all the commands I can use not only commands for everyone.

**Comment by ostorc** [comment]
Fixed
