### ISSUE TITLE
Commands in #bot-spam

### ISSUE THREAD

**Issue by LucyAnne98** [fit-ctu-discord/honza-botner#97]
Pls pls pls pls ať fungují commands v #bot-spam a naopak ve voice ať je jen diskuze a ne bot spam :D Děkuji převelice <3

**Comment by pokorj54** [comment]
bot spam není určen pro honzu botnera

**Comment by tenhobi** [comment]
We should definitelly add `#bot-commands` (id `681560465066688523`). Not sure about `#bot-spam` (id `774247506669600798`).

**Comment by tenhobi** [comment]
We added channel `#voice-commands` and now you can only add and edit voice in that one and `#bot-commands` channels.
